openapi: 3.0.3
info:
  title: Restaurant API
  description: API for managing Restaurant
  version: 1.0.0
  contact:
    email: tsilavina.3@mail.hei.school

servers:
  - url: https://api.restaurant/TD5
    description: Production server
  - url: http://localhost:8080/TD5
    description: Local development server

paths:
  /ingredients:
    get:
      tags: [Ingredients]
      summary: List ingredients with filtering and pagination
      parameters:
        - $ref: '#/components/parameters/priceMinFilter'
        - $ref: '#/components/parameters/priceMaxFilter'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        '200':
          description: Paginated ingredient list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedIngredients'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

    post:
      tags: [Ingredients]
      summary: Create new ingredients
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/IngredientCreate'
      responses:
        '201':
          description: Ingredients created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /ingredients/{ingredientId}:
    get:
      tags: [Ingredients]
      summary: Get ingredient details
      parameters:
        - $ref: '#/components/parameters/ingredientId'
      responses:
        '200':
          description: Ingredient details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /ingredients/{ingredientId}/prices:
    put:
      tags: [Prices]
      summary: Update ingredient prices
      parameters:
        - $ref: '#/components/parameters/ingredientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/PriceUpdate'
      responses:
        '200':
          description: Prices updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Price'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /ingredients/{ingredientId}/stock-movements:
    put:
      tags: [Stock]
      summary: Update stock movements
      parameters:
        - $ref: '#/components/parameters/ingredientId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/StockMovementUpdate'
      responses:
        '200':
          description: Stock movements updated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StockMovement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /dishes:
    get:
      tags: [Dishes]
      summary: List dishes with current ingredient prices, stock, and required quantities
      responses:
        '200':
          description: List of dishes with ingredients and quantities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dish'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /dishes/{id}/ingredients:
    put:
      tags: [Dishes]
      summary: Update dish ingredients with their quantities
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Dish identifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DishIngredientUpdate'
      responses:
        '200':
          description: Ingredients for the dish updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DishIngredientRest'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'
  /orders/{reference}:
    get:
      tags: [Orders]
      summary: Get order by reference with dish details
      parameters:
        - name: reference
          in: path
          required: true
          schema:
            type: string
          description: Order reference
      responses:
        '200':
          description: Order found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetails'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ServerError'

  /orders/{reference}/dishes:
    put:
      tags: [Orders]
      summary: Modifier la liste des plats d'une commande (quantités + statut commande)
      parameters:
        - name: reference
          in: path
          required: true
          schema:
            type: string
          description: Référence de la commande à modifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateOrderDishesRequest'
      responses:
        '200':
          description: Commande mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetails'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

  /orders/{reference}/dishes/{dishId}:
    put:
      tags: [Orders]
      summary: Mise à jour du statut d’un plat spécifique dans une commande
      description: Permet de modifier le statut d’un plat dans une commande donnée (IN_PROGRESS, FINISHED, DELIVERED)
      parameters:
        - name: reference
          in: path
          required: true
          schema:
            type: string
          description: Référence de la commande
        - name: dishId
          in: path
          required: true
          schema:
            type: integer
          description: ID du plat dont on veut changer le statut (pas l’ID de l’instance dans la commande)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDishStatusRequest'
      responses:
        '200':
          description: Statut du plat mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DishOrderStatus'
        '404':
          $ref: '#/components/responses/NotFound'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    # Core Models
    Ingredient:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "Saucisse"
        actualPrice:
          type: number
          format: double
          example: 20.0
        availableQuantity:
          type: number
          format: double
          example: 10000.0
        prices:
          type: array
          items:
            $ref: '#/components/schemas/Price'
        stockMovements:
          type: array
          items:
            $ref: '#/components/schemas/StockMovement'
      required: [id, name, actualPrice, availableQuantity]

    Price:
      type: object
      properties:
        id:
          type: string
          nullable: true
          example: null
        price:
          type: number
          format: double
          example: 20.0
        dateValue:
          type: string
          format: date
          example: "2025-01-01"
      required: [price, dateValue]

    StockMovement:
      type: object
      properties:
        id:
          type: string
          example: "1"
        quantity:
          type: number
          format: double
          example: 10000.0
        unit:
          type: string
          enum: [G, L, U]
          example: G
        type:
          type: string
          enum: [IN, OUT]
          example: IN
        creationDatetime:
          type: string
          format: date-time
          example: "2025-02-01T05:00:00Z"
      required: [id, quantity, unit, type, creationDatetime]

    # Input Models
    IngredientCreate:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "New Ingredient"
      required: [name]

    PriceUpdate:
      type: object
      properties:
        price:
          type: number
          format: double
          example: 25.0
        dateValue:
          type: string
          format: date
          example: "2025-01-02"
      required: [price, dateValue]

    StockMovementUpdate:
      type: object
      properties:
        id:
          type: string
          example: "1"
        quantity:
          type: number
          format: double
          example: 500.0
        unit:
          type: string
          enum: [G, L, U]
          example: G
        type:
          type: string
          enum: [IN, OUT]
          example: IN
      required: [quantity, unit, type]

    # Response Wrappers
    PaginatedIngredients:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Ingredient'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          example: 5
        totalPages:
          type: integer
          example: 1
    Dish:
      type: object
      properties:
        id:
          type: string
          example: "1"
        actualPrice:
          type: number
          format: double
          example: 1500.0
        ingredientsCost:
          type: number
          format: double
          example: 40000
        name:
          type: string
          example: "Spaghetti Saucisse"
        availableQuantity:
          type: number
          format: double
          example: 50.0
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/DishIngredient'
      required: [id, name, availableQuantity, ingredients]

    DishIngredient:
      type: object
      properties:
        id:
          type: string
          example: "1"
        name:
          type: string
          example: "Saucisse"
        actualPrice:
          type: number
          format: double
          example: 20.0
        unit:
          type: string
          enum: [G, L, U]
          example: G
        availableQuantity:
          type: number
          format: double
          example: 10000.0
        requiredQuantity:
          type: number
          format: double
          example: 200.0
      required: [id, name, actualPrice, availableQuantity, requiredQuantity]

    DishIngredientUpdate:
      type: object
      properties:
        ingredientId:
          type: string
          example: "1"
        requiredQuantity:
          type: number
          format: double
          example: 250.0
        unit:
          enum: [G, L, U]
          example: U
      required: [ingredientId, requiredQuantity]

    DishIngredientRest:
      type: object
      properties:
        ingredientId:
          type: string
          example: "1"
        name:
          type: string
          example: "Pain"
        requiredQuantity:
          type: number
          format: double
          example: 250.0
        unit:
          enum: [G, L, U]
          example: U
        actualPrice:
          type: number
          format: double
          example: 20.0
        availableQuantity:
          type: number
          format: double
          example: 10000.0
      required: [ingredientId, name, requiredQuantity, unit, actualPrice, availableQuantity]


    OrderDetails:
      type: object
      properties:
        reference:
          type: string
          example: "ORD123456"
        status:
          type: string
          example: "Pending"
        totalAmount:
          type: number
          format: double
          example: "3000.0"
        dishes:
          type: array
          items:
            $ref: '#/components/schemas/OrderDish'
      required: [reference, status, totalAmount, dishes]

    OrderDish:
      type: object
      properties:
        idDish:
          type: string
          example: "1"
        name:
          type: string
          example: "Pizza Margherita"
        currentPrice:
          type: number
          format: double
          example: 12.5
        quantity:
          type: integer
          example: 2
        status:
          type: string
          example: "Ready"
      required: [idDish, name, currentPrice, quantity, status]

    UpdateOrderDishesRequest:
      type: object
      properties:
        status:
          type: string
          enum: [CREATED, CONFIRMED]
          example: "CONFIRMED"
        dishes:
          type: array
          description: Liste des plats avec quantité à commander
          items:
            $ref: '#/components/schemas/OrderDishInput'
      required: [status, dishes]

    OrderDishInput:
      type: object
      properties:
        dishId:
          type: integer
          example: 3
        quantity:
          type: integer
          example: 2
      required: [dishId, quantity]

    UpdateDishStatusRequest:
      type: object
      properties:
        status:
          type: string
          enum: [IN_PROGRESS, FINISHED, DELIVERED]
          example: "IN_PROGRESS"
      required: [status]

    DishOrderStatus:
      type: object
      properties:
        dishId:
          type: integer
          example: 4
        reference:
          type: string
          example: "ORD123"
        status:
          type: string
          enum: [IN_PROGRESS, FINISHED, DELIVERED]
          example: "IN_PROGRESS"

    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: "2025-02-01T10:00:00Z"
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "Invalid price filter range"
        path:
          type: string
          example: "/v1/ingredients"


  parameters:
    ingredientId:
      name: ingredientId
      in: path
      required: true
      schema:
        type: string
      description: Ingredient identifier
      example: "1"

    priceMinFilter:
      name: priceMinFilter
      in: query
      required: false
      schema:
        type: number
        format: double
        minimum: 0
      description: Minimum price filter (inclusive)
      example: 10.0

    priceMaxFilter:
      name: priceMaxFilter
      in: query
      required: false
      schema:
        type: number
        format: double
        minimum: 0
      description: Maximum price filter (inclusive)
      example: 1000.0

    page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
      description: Page number (0-indexed)
      example: 0

    size:
      name: size
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 100
        default: 20
      description: Items per page
      example: 10

  responses:
    BadRequest:
      description: Invalid request parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
